# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10AwkWRgK8mh47oAp_BwzBP1b4loO_AcF
"""

a = float(input())
b = float(input())
c = float(input())
x = float(input())

y = a * x * x + b * x + c
print(y)