# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10AwkWRgK8mh47oAp_BwzBP1b4loO_AcF
"""

a=5
b=7
c=6
x=7
y=a*x*x+b*x+c
print(y)